#!/usr/local/bin/bash
#!/usr/bin/env bash
echo $SHELL
GVM_RC="[[ -s "$HOME/.gvm/scripts/gvm" ]] && source $HOME/.gvm/scripts/gvm"
function check_root () {
  if [[ $EUID -ne 0 ]]; then
    echo "This script must be run as root" 
    exit 1
  fi
}
check_root
function LOAD_GO() {
        export GOPATH=$HOME/go
        export PATH=$PATH:$GOPATH/bin
	[[ -s "$HOME/.gvm/scripts/gvm" ]] && source $HOME/.gvm/scripts/gvm
	echo "GVM_ROOT $GVM_ROOT"
	ls $HOME/.gvm/scripts/gvm
}
function INSTALL_GO() {
	[[ -z `which gvm` ]] && bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
	gvm install go1.15.6
        local rc="rc"
        local SHELL_FILE=/etc/$SHELL$rc
        [[ -z `grep -o "$GVM_RC" /etc/profile` ]] && echo "$GVM_RC" >> /etc/profile
        case $SHELL in
                "bash" )
                   [[ -z `grep -o "$GVM_RC" $SHELL_FILE` ]] && echo "$GVM_RC" >> $SHELL_FILE
                   ;;
                "sh" )
                   [[ -z `grep -o "$GVM_RC" /etc/profile` ]] && echo "$GVM_RC" >> /etc/profile
                   ;;
                "zsh" )
                   [[ -z `grep -o "$GVM_RC" $SHELL_FILE` ]] && echo "$GVM_RC" >> $SHELL_FILE
                   ;;
                "*" )
                   [[ -z `grep -o "$GVM_RC" $SHELL_FILE` ]] && echo "$GVM_RC" >> $SHELL_FILE
                   ;;
        esac
        mkdir -p $HOME/go/{bin,src}
	LOAD_GO
}
function STOP_DNS() {
        echo "Stopping dns $SERVICE"
        ps -ax | grep dnsproxy | grep -v 'grep' | awk '{print $1}' | xargs sudo kill -9
        sudo launchctl stop $SERVICE.startup
        sudo launchctl stop $SERVICE.reloaded
        sudo launchctl unload -w /Library/LaunchDaemons/$SERVICE.plist
        sudo launchctl unload -w /Library/LaunchDaemons/$SERVICE.startup.plist
}
function PRE_START_DNS() {
	(ifconfig lo0 alias 192.168.123.9/32 up)&
        ifconfig lo0 alias 192.168.123.8/32 up
}
function PRE_STOP_DNS() {
	(ifconfig lo0 alias 192.168.123.9/32 down)&
        ifconfig lo0 alias 192.168.123.8/32 down
}
function START_DNS(){
        echo "Starting dns $SERVICE"
        sudo launchctl load -w /Library/LaunchDaemons/$SERVICE.plist
        sudo launchctl load -w /Library/LaunchDaemons/$SERVICE.startup.plist
        sudo launchctl start $SERVICE.startup
        sudo launchctl start $SERVICE.reloaded
}
function RESTART_DNS() {
        echo "Restating dns $SERVICE"
        STOP_DNS
        START_DNS
}
function LIST_DNS() {
	sudo launchctl list | grep -i dns
}
function INSTALL_DNS_BINARY() {
	go get github.com/AdguardTeam/dnsproxy
}
function UPDATE_DNS_BINARY() {
	INSTALL_DNS_BINARY
#	RESTART_DNS
}
export -f STOP_DNS
export -f START_DNS

export -f PRE_STOP_DNS
export -f PRE_START_DNS
export -f RESTART_DNS
export -f LIST_DNS

export -f INSTALL_GO
export -f LOAD_GO

export -f UPDATE_DNS_BINARY
export -f INSTALL_DNS_BINARY

export -f check_root
