# Try UDP first, if truncated use the alernative (TCP)
[groups.ctp-dns_all-retry]
type = "truncate-retry"
resolvers = [ "ctp-dns_all-dtls" ]
retry-resolver = "ctp-dns_all-dot"

[groups.ctp-dns_gcp-retry]
type = "truncate-retry"
resolvers = [ "ctp-dns_gcp-dtls" ]
retry-resolver = "ctp-dns_gcp-dot"

[groups.ctp-dns-fastest]
type   = "fastest"
resolvers = [
	"ctp-dns_all-dot",
	"ctp-dns_all-dtls",
	"ctp-dns_all-doq",
	"ctp-dns_all-doh-post",
	"ctp-dns_all-doh-get",
	"ctp-dns_gcp-dot",
	"ctp-dns_gcp-dtls",
	"ctp-dns_gcp-doq",
	"ctp-dns_gcp-doh-post",
	"ctp-dns_gcp-doh-get",
]

[groups.ctp-dns-fail-back]
type = "fail-back"
resolvers = [
	"ctp-dns-fastest",
	"ctp-dns-fail-rotate",
	"ctp-dns-fastest-raw",
	"ctp-dns-fail-back-raw",
	"ctp-dns-backup-fastest",
	"ctp-dns-backup-fail-back",
]
servfail-error = true
reset-after = 60

[groups.ctp-dns-fail-rotate]
type = "fail-rotate"
resolvers = [
	"ctp-dns_all-retry",
	"ctp-dns_all-dot",
	"ctp-dns_all-dtls",
	"ctp-dns_all-doq",
	"ctp-dns_all-doh-post",
	"ctp-dns_all-doh-get",
	"ctp-dns_gcp-retry",
	"ctp-dns_gcp-dot",
	"ctp-dns_gcp-dtls",
	"ctp-dns_gcp-doq",
	"ctp-dns_gcp-doh-post",
	"ctp-dns_gcp-doh-get",
]
servfail-error = true
reset-after = 60
