[listeners.local-udp-1]
address = "192.168.123.9:53"
protocol = "udp"
resolver = "ctp-dns-cached"

[listeners.local-tcp-1]
address = "192.168.123.9:53"
protocol = "tcp"
resolver = "ctp-dns-cached"

[listeners.local-udp-2]
address = "192.168.123.8:53"
protocol = "udp"
resolver = "ctp-dns-cached"

[listeners.local-tcp-2]
address = "192.168.123.8:53"
protocol = "tcp"
resolver = "ctp-dns-cached"
